### ISSUE TITLE
Add docs for how to get started

### ISSUE THREAD

**Issue by rlvoyer** [lassik/emacs-format-all-the-code#111]
Hi there! Thanks for this package! I'm trying to figure out how to use it exactly. (I'm still a bit of an elisp newb.) I set up some .dir-locals in a Scala project, though I'm clearly doing something wrong. Here's what the .dir-locals.el file looks like:

```lisp
((nil
  (format-all-formatters
   ("Scala" . scalafmt))))
```

Is that reasonable? What is the value in that alist? And how should I expect it to behave? Will formatting happen automatically on save? Do I need to add anything to my .emacs file?

Thanks so much for your time!

**Comment by lassik** [comment]
It should work if you remove the dot:

```Emacs Lisp
((nil
  (format-all-formatters
   ("Scala" scalafmt))))
```

Now if you visit a Scala file in that directory, Emacs will ask you whether to apply those local variables; say `y` for yes, or `!` to always use them and not ask each time.

In the buffer with your Scala file, try `M-x format-all-buffer` to format it once, or `M-x format-all-mode` to format every time you save the file.

It's possible to add `format-all-mode` to `prog-mode-hook`. In that case `format-all-mode` will be automatically enabled for most programming language modes (including Scala) and you don't need to do `M-x` manually each time you open a file.
