### ISSUE TITLE
Dockerfile formatter not working

### ISSUE THREAD

**Issue by AirManH** [lassik/emacs-format-all-the-code#113]
`format-all-buffer` can not format `Dockerfile` , the buffer `*format-all-errors*` prints `Please pass in Dockerfile(s)`

## Steps to reproduce the problem

1. In `init file`:

   ``` emacs lisp
   (use-package format-all)
   ```
2. Open `Dockerfile`, `M-x`, `fotmat-all-buffer`, choose `dockfmt`.
3. The buffer `*format-all-errors*` prints:
   ``` text
   Please pass in Dockerfile(s)
   ```

## Specification

1. GNU Emacs 27.1
2. format-all.el 20210107.1425
3. dockfmt v0.3.3
4. Arch Linux

**Comment by AirManH** [comment]
I guess it's because `dockfmt fmt` (at least `v0.3.3`) can not read from `stdin`.

Here is my test:

``` bash
echo "RUN ls" | dockfmt fmt   
Please pass in Dockerfile(s)
```

**Comment by lassik** [comment]
Indeed, 0.3.3 cannot read from stdin. You need to get the latest version of dockfmt from the git master branch of https://github.com/jessfraz/dockfmt It's been quite a while since the last release, so maybe if you ask them you can convince them to make a new release.

**Comment by AirManH** [comment]
Now I can get the latest version from [here](https://aur.archlinux.org/packages/dockfmt-git/), so I decide to close this issue.
