### ISSUE TITLE
Error with latest version on nativecomp emacs branch

### ISSUE THREAD

**Issue by egh** [lassik/emacs-format-all-the-code#114]
I'm not sure if this is a bug with this package, inhertenv, or with the emacs nativecomp branch, but I figured I'd get it started here.

Steps to reproduce:

1. Open `.js` file.
2. `M-x format-all-buffer` then choose `standard` (those this probably doesn't matter)
3. Result: error

```
Debugger entered--Lisp error: (invalid-function inheritenv)
  inheritenv(("/*\n * Copyright (c) 2017 Public Library of Science..." "standard: Use JavaScript Standard Style (https://s..."))
  format-all--buffer-thunk(#f(compiled-function (input) #<bytecode 0x8fedd923afe6ef3>))
  format-all--buffer-hard((0 1) ".*?:.*?:[0-9]+:[0-9]+: Parsing error:" nil "/home/egh/.nvm/versions/node/v12.13.0/bin/standard" "--fix" "--stdin")
  #f(compiled-function (executable language) #<bytecode 0xaa385e72a986f31>)("/home/egh/.nvm/versions/node/v12.13.0/bin/standard" "JavaScript")
  #f(compiled-function () #<bytecode 0x1184dae159b06705>)()
  format-all--save-line-number(#f(compiled-function () #<bytecode 0x1184dae159b06705>))
  format-all--run-chain("JavaScript" (standard))
  format-all-buffer(t)
  funcall-interactively(format-all-buffer t)
  command-execute(format-all-buffer record)
  execute-extended-command(nil "format-all-buffer" nil)
  funcall-interactively(execute-extended-command nil "format-all-buffer" nil)
  command-execute(execute-extended-command)
```

**Comment by lassik** [comment]
@purcell Do you understand what's going on here? I don't :)

**Comment by purcell** [comment]
That's very strange. I'm also on a bleeding-edge nativecomp build and while I haven't tried `standard` specifically, if I set things up with a failing formatter (`elm-format` in my case) then I don't get this issue at all: the failure is handled gracefully. I wonder if this is a case of a manual installation where `inheritenv` isn't actually installed?

**Comment by egh** [comment]
It also fails with using the black formatter for python.

Evalling `(inheritenv (message "huh"))` works fine for me.

I'm not on the bleeding edge, I'm using the snap package. Let me try building from git.

**Comment by egh** [comment]
Still getting the error with the latest git version (a8b8d220b4fccaa812e85f9b2b3715593dc285ac). I'm trying to isolate it more

**Comment by egh** [comment]
I deleted my `.emacs.d/eln-cache` directory. It worked before the code was compiled but failed after it was compiled. @purcell are you sure you are running a native compiled `inheritenv`?

**Comment by purcell** [comment]
Okay, here's what I think happened here:

- It's not about native compilation, I believe
- When the installation of both packages happens in the same "package.el" pass, the autoload of the "inheritenv" macro is not evaluated before "format-all" is compiled.
- "format-all" doesn't `require` "inheritenv", so it assumes that "inheritenv" is a function that will be called by name runtime, but no such function exists.

The fix was to explicitly `require` "inheritenv", which is the best thing to do anyway. Perhaps I'll remove the autoload of that macro to avoid any confusion.

**Comment by purcell** [comment]
#115 should fix this.

**Comment by lassik** [comment]
Whoa, don't know how I neglected to add the `(require ...)`. Thanks for spotting it! Now pushed to MELPA.

**Comment by egh** [comment]
Works for me now! Thank you both.
