### ISSUE TITLE
How to use formatters' command line arguments?

### ISSUE THREAD

**Issue by drcxd** [lassik/emacs-format-all-the-code#116]
I could only use the default formatting pattern now. Since the program depends on external formatter, is there any way I could pass additional arguments to these external formatter to configure the formatting pattern?

**Comment by lassik** [comment]
Yes, custom command line arguments can be passed. Try something like the following in a `.dir-locals.el` file in the directory of your project:

```
((nil
  (format-all-formatters
   ("Python" (black "--skip-string-normalization")))))
```

Replace `"Python"`, `black` and `"--skip-string-normalization"` with the language, formatter, and arguments you want.

**Comment by lassik** [comment]
It's also possible to set the `format-all-formatters` variable in Emacs Lisp (e.g. in a hook function).

**Comment by drcxd** [comment]
Thanks!

**Comment by drcxd** [comment]
Is there any way to set the `format-all-formatters` globally in a config file? I almost know nothing about emacs-lisp and I tried `setq` and `set-variable` but neither of them worked. I know using the per-project setting file is good practice, but I still want to know how could I set a global default option?
