### ISSUE TITLE
swiftformat doesn't refer to .swiftformat config at root of my project

### ISSUE THREAD

**Issue by tomoyukim** [lassik/emacs-format-all-the-code#121]
Hi, I've tried to apply swiftformat with `.swiftformat` config file at root of my iOS project, however it seems not to use the config. (e.g. intent level 4 is applied as default instead of 2 in my config file). Do you have any way to resolve config file path for the formatter?

**Comment by lassik** [comment]
Fixed in the above commit and tested that it works on my computer. Let me know if the fix doesn't work for you.

**Comment by tomoyukim** [comment]
Thank you for your quick response! It works fine for me, too.
