### ISSUE TITLE
Don't popup error buffer

### ISSUE THREAD

**Issue by asif-mahmud** [lassik/emacs-format-all-the-code#123]
Hi, whenever i try to save a buffer with say there are some syntax errors, format-all pops up a new buffer named **format-all-errors**. I have to close that window explicitly every time that happens. Is there any way to hide that buffer ? I am not sure what else to provide with to help you recreate it, so please let me know if you need some info specifically. But i think you already know what i am talking about. Anyway, if theres a solution please tell, thanks in advance.

**Comment by lassik** [comment]
> Is there any way to hide that buffer?

No, there isn't. Setting `format-all-always-show-errors` to `nil` hides the error buffer, but only when there are no errors.

We could rename that variable to `format-all-show-errors`, with the choices:

* `always` - show the buffer even when no errors/warnings
* `errors` - show the buffer whenever there are errors
* `warnings` - show the buffer whenever there are errors/warnings
* `never` - don't show the buffer even if there are errors

**Comment by lassik** [comment]
We could also add a hook to customize it per formatter, but formatters are open source, so if there are problems with individual formatters it would be better to fix them to emit more reasonable output.

**Comment by asif-mahmud** [comment]
adding `format-all-show-errors` option would be great, but i tried `format-all-always-show-errors` set to `nil` didn't stop opening that window.

**Comment by lassik** [comment]
Setting `format-all-always-show-errors` to `nil` doesn't help if you get error messages; that setting only hides an empty error buffer.

> how do you suggest to detect `warnings` ?

Good question. The simplest approach is to check whether the exit code from the formatter was success (zero) or failure (non-zero).

* If the exit code indicated failure, then assume at least one error message was written to stderr.
* If the exit code indicated success, yet the formatter wrote messages to stderr anyway, assume those are warnings, not errors.

**Comment by lassik** [comment]
If you'd like to make a PR, that would be appreciated! It's OK to change the name of the setting from `format-all-always-show-errors` to `format-all-show-errors`.

It should work to change the logic for setting `show-errors-p` in `format-all--update-errors-buffer`:

* if `(eq status :error)` - formatter encountered errors
* else if `(not (= 0 (length error-output)))` - formatter encountered warnings
* else - formatter succeeded

**Comment by asif-mahmud** [comment]
great.

**Comment by asif-mahmud** [comment]
#126

**Comment by lassik** [comment]
#126 has been merged, so closing. Thanks for implementing this.
