### ISSUE TITLE
Is there any easy way to set line length through format-all config

### ISSUE THREAD

**Issue by bataak** [lassik/emacs-format-all-the-code#125]
All different formatters have their own default line length. But I'm curious about the simplest way to change their default length in my format-all config file. Thanks in advance!

**Comment by lassik** [comment]
There is no such setting in format-all itself. Some formatters wrap long lines, others don't. The ones that do, tend to have their own line length setting. For the ones that don't, there is no easy way to wrap lines without knowing details about the particular programming language that is formatted.

Format-all will be most reliable and easiest to understand if it just runs the existing formatters and doesn't add its own custom formatting on top of them. If you need line length for a particular language whose formatter doesn't have that feature, it's best to contact the authors of that formatter to ask if they can add it.

Line wrapping may be [the most difficult feature](http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/) to add to a formatter, but not impossible; e.g. clang-format has it.

**Comment by lassik** [comment]
If you're simply asking whether it's possible to have one line-length setting to cover all the formatters that already each have their own setting, that would certainly be possible; the [Unibeautify](https://unibeautify.com/) project does that. I wrote an [Emacs mode](https://github.com/Unibeautify/emacs), which IIRC works but is not yet in MELPA. I have some ideas for what to do to unify formatters but haven't got around to implementing anything. The Unibeautify configuration format would be the best starting point.

**Comment by bataak** [comment]
Thanks for the reply. Unibeatify is great tool but heavy. Anyway I like your plugin, and hope coming up with a solution to the formatters which have their own line length settings, for example black.

**Comment by lassik** [comment]
Format-all is meant to be a lightweight, un-opinionated wrapper over existing formatters so it's not the right place to experiment with features like a common line-length setting for all formatters. It's best to tackle problems like that in other projects such as Unibeautify.

However, format-all does let you give custom command line arguments to formatters, so if your favorite formatter has a line-length setting you can use it. To set the line length for Black you can put something like this in `.dir-locals.el`:

```
((nil
  (format-all-formatters
   ("Python" (black "--line-length" "70")))))
```

You can also `(setq format-all-formatters '(("Python" (black "--line-length" "70"))))` in a hook function.

**Comment by bataak** [comment]
Great, thank you!
