### ISSUE TITLE
LaTeX formatting

### ISSUE THREAD

**Issue by bataak** [lassik/emacs-format-all-the-code#127]
Hi, I'm newbie in emacs and struggling with using AucTeX LaTeX-fill-buffer formatter instead of latexindent. Do you have any idea to use it? Thanks in advance!

**Comment by lassik** [comment]
Done. You can now select an `auctex` formatter in `latex-mode` buffers.

**Comment by bataak** [comment]
Perfect! Would you mind correcting me to change default `LaTeX` formatter?

```
(setq format-all-default-formatters '(("LaTeX" auctex)))
```

**Comment by lassik** [comment]
It's probably easiest to change it from `M-x customize-group format-all`.
