### ISSUE TITLE
R styler  Error in file(stdin) : invalid 'description' argument

### ISSUE THREAD

**Issue by AdamCottrill** [lassik/emacs-format-all-the-code#129]
I was unable to get the R-formatter "styler" to work in a normal ESS[R] buffer, receiving the error: "Error in file(stdin) : invalid 'description' argument".

I was able to address the issue and get styler to work as expected by updating the format-all-function below by replacing the escaped double quotes with un-escaped single quotes (or adding triple slashes ahead of the double quotes):

    (define-format-all-formatter styler
      (:executable "Rscript")
      (:install "Rscript -e 'install.packages(\"styler\")'")
      (:languages "R")
      (:format
       (format-all--buffer-easy
        executable "--vanilla"
        "-e" (concat
              "options(styler.colored_print.vertical=FALSE);"
              ;;" con <- file(\"stdin\");"
              ;;" con <- file(\\\"stdin\\\");" ;; This worked too
              " con <- file('stdin');"
              " out <- styler::style_text(readLines(con));"
              " close(con);"
              " out"))))

I am not sure how compatible this is with other operating systems but thought I would report here just in case others were receiving the same error message.

+ Windows 10 
+ Emacs 26.3

Adam

**Comment by lassik** [comment]
Thanks for reporting the bug. I don't know what causes it - the old quoting worked on my computer. It may be a Unix vs Windows issue. Anyway, the single-quote version works for me as well. Since it's more compatible, I changed it. Let me know in case this doesn't solve your problem.
