### ISSUE TITLE
Dart formatter changed from `dartfmt` to `dart format`

### ISSUE THREAD

**Issue by syvanpera** [lassik/emacs-format-all-the-code#130]
I'm just getting into dart and flutter and looks like the plugin uses `dartfmt` for formatting dart code. I believe the new standard way is to use `dart format` command.

**Comment by lassik** [comment]
OK. Is `dart format --stdin-name example.dart` the right way to call the formatter now?

**Comment by syvanpera** [comment]
Actually I'm not sure. I couldn't get the formatting to work at first but then I noticed that if I installed the dart sdk directly, it still contained the dartfmt command. The binaries that come with flutter don't. And then I ran into this page: https://dart.dev/tools/dart-format which says that `dart format` replaces `dartfmt`

**Comment by lassik** [comment]
Maybe we should have both for the time being, and make `dart format` the default.

**Comment by lassik** [comment]
Here's the command line usage for `dart format`:

```
 dart format --help
Idiomatically format Dart source code.

Usage: dart format [options...] <files or directories...>
-h, --help                     Print this usage information.
-v, --verbose                  Show all options and flags with --help.
-o, --output                   Set where to write formatted output.

          [json]               Print code and selection as JSON.
          [none]               Discard output.
          [show]               Print code to terminal.
          [write] (default)    Overwrite formatted files on disk.

    --set-exit-if-changed      Return exit code 1 if there are any formatting changes.
    --fix                      Apply all style fixes.
-l, --line-length              Wrap lines longer than this.
                               (defaults to "80")

Run "dart help" to see global options.
```

I can't figure out how to make it format stdin to stdout (without using the non-portable Unix device `/dev/stdin`).

**Comment by meain** [comment]
You can do one of these:
```bash
dart format filename.dart --output show  # format file
dart format --output show <filename.dart  # format stdin
```

**Comment by lassik** [comment]
The above PR added `dart format` and made it the default.

We should probably delete `dartfmt` after some time, since it looks like it's deprecated.
