### ISSUE TITLE
Disable sorting of `bibtex` keys

### ISSUE THREAD

**Issue by swarnendubiswas** [lassik/emacs-format-all-the-code#135]
It will be good if the package exposes a user option to control the sorting of `bibtex` entries based on the key. Personally, I would like to keep sorting disabled and will prefer only aligning the entries.

**Comment by lassik** [comment]
Since we now support formatter chaining, `bibtex` and `bibtex-sort` could be two different formatters. Then everyone can choose whether they want sorting or not.

**Comment by swarnendubiswas** [comment]
Okay. Could you share some more details? How could I set up the package to disable sorting of entries, but sort individual items within an entry?

**Comment by lassik** [comment]
I don't use the bibtex formatter myself so I don't understand what that means. If you sort the individual items manually, does the reformatter mess up the sort order?

**Comment by swarnendubiswas** [comment]
This is what I mean. Consider the following example `.bib` file.

```
@inproceedings{weak-racedet-isca-1991,
  author       = {Adve, Sarita V. and Hill, Mark D. and Miller, Barton P. and Netzer, Robert H. B.},
  title        = {{Detecting Data Races on Weak Memory Systems}},
  booktitle    = ISCA,
  year         = 1991,
  pages        = {234--243},
  xaddress     = {New York, NY, USA},
  xpublisher   = {ACM},
  xdoi         = {10.1145/115952.115976},
  isbn         = {0-89791-394-9},
  xlocation    = {Toronto, Ontario, Canada}
}

@inproceedings{abadi-tm-ppopp-2009,
  author       = {Abadi, Mart{\'i}n and Harris, Tim and Mehrara, Mojtaba},
  title        = {{Transactional Memory with Strong Atomicity Using Off-the-Shelf Memory Protection
                  Hardware}},
  booktitle    = PPOPP,
  year         = 2009,
  pages        = {185--196},
  xaddress     = {New York, NY, USA},
  xpublisher   = {ACM},
  xdoi         = {10.1145/1504176.1504203},
  isbn         = {978-1-60558-397-6},
  xlocation    = {Raleigh, NC, USA}
}
```

If I run `format-all-buffer`, then the two entries are swapped since they are sorted by the key text (`aba...` and `weak...`). I was wondering whether we can disable sorting of the complete entries and instead align and format just the keys within an entry (e.g., booktitle, year, pages). `LaTeX Workshop` can do that with `latexindent` IIRC.
