### ISSUE TITLE
Config errors with default installation

### ISSUE THREAD

**Issue by theSherwood** [lassik/emacs-format-all-the-code#137]
On an html buffer, I get the following errors when I run `format-all-buffer`:

```
Config: unknown option: drop-empty-elements
Error: Can't open "no"

Config: missing or malformed argument for option: show-body-only
Error: Can't open "auto"

Config: unknown option: indent-with-tabs
Error: Can't open "no"
```

I haven't added any config for this package. So I'm unsure of what might be going wrong here.

**Comment by lassik** [comment]
Try turning on debug mode (`M-x customize-variable format-all-debug`), then doing `M-x format-all`. It will write debug information at the end of the `*Messages*` buffer. Can you paste that info here? Specifically, it looks like you're passing custom command line arguments to the formatter and format-all is not passing them properly.

**Comment by theSherwood** [comment]
Hmm. I'm not sure what's going on. I have commands for `M-x format-all-buffer` and `M-x format-all-mode`, but I don't have any `M-x format-all`. I also don't seem to have any `format-all-debug` variable that I can customize.

I'm wondering if this is a result of using Doom emacs. Maybe it is using an older version of this package.

**Comment by lassik** [comment]
Sorry, I means `M-x format-all-buffer` not `M-x format-all`.

Unfortunately I usually can't help with Doom Emacs related problems. They use some kind of custom packaging of format-all that I know nothing about. Your best bet is to ask on Doom's issue tracker; maybe they can solve the problem.

**Comment by lassik** [comment]
You're welcome
