### ISSUE TITLE
After invoke `format-all-buffer`,  `ts-ls` language server get disconnected

### ISSUE THREAD

**Issue by YUFENGWANG** [lassik/emacs-format-all-the-code#139]
I'm using `doom emacs`, when i invoke the `format-all-buffer` command after editing `js` file, the `ts-ls` language server get disconnected, `lsp` feature not working since then, such as `auto-completion`

**Comment by lassik** [comment]
Sorry, I don't know how to help with Doom Emacs -related issues. Your best bet is to try asking in Doom's issue tracker.
