### ISSUE TITLE
Use signal instead of error

### ISSUE THREAD

**Issue by qoops-1** [lassik/emacs-format-all-the-code#140]
It would be nice if errors would have distinct error-symbols, not the generic `error` one. My usecase for this is that I want to format buffers on save and if a formatter executable is not available then I would like it to silently fail (maybe producing a warning), instead of producing an error, thus I need a way to safely catch the error. It would be much easier to do if I could match the error via error-symbol.

If you're alright with this, I can open a PR to fix this

**Comment by lassik** [comment]
So use custom condition types instead of generic condition types? Sounds like the right thing for sure! A PR would be much appreciated.
