### ISSUE TITLE
Use of regexp-or in Ruby formatters

### ISSUE THREAD

**Issue by lassik** [lassik/emacs-format-all-the-code#144]
@knu The [`format-all--buffer-hard-ruby`](https://github.com/lassik/emacs-format-all-the-code/blob/43e735bc1a8d3bc242d200d43351aa74c4e86997/format-all.el#L502) function is using `regexp-or` which is not defined in my copy of Emacs. Could we use a more conventional function instead, e.g. `regexp-opt`?

**Comment by knu** [comment]
Ah, my bad.  It's from an ancient library I'm still using.  I'll fix that.  By the way, 43e735bc broke execution with bundler, so I'll fix that as well.
