### ISSUE TITLE
Can't save at all if format fails

### ISSUE THREAD

**Issue by billop** [lassik/emacs-format-all-the-code#146]
So if I enable format-all-mode for python, but I don't have "black" installed, which I have set as my formatter, I will get `peculiar error` and emacs will fail to save the file. I can save the file once I disable format-all-mode but it shouldn't be this way. It should just raise an error and let me save.

**Comment by 2jt** [comment]
Hi @billop and @lassik, I've got bitten by this too and it was really confusing as I was assuming the file was saved, even it wasn't because of this error `peluciar error` thing. 
This happens when the formatter binary is not found on the machine.

**Comment by lassik** [comment]
We changed from `(error ...)` to `(signal ...)` in issue #140 / PR #141.

I'm not familiar with this part of Emacs Lisp. Is it possible to keep the custom error symbol, but avoid the `peculiar error` thing and let people save anyway? Would `(define-error ...)` work?

**Comment by lassik** [comment]
@2jt @billop please check out if the above commit (just pushed to master) fixes your problem.

**Comment by 2jt** [comment]
@lassik Great. I have never used signal and actually didn't bother to look too much it :) (changing it to `error` was enough to fix the issue).

**Comment by lassik** [comment]
It used to be `(error ...)` but someone said a generic "error" is not specific enough, so we changed it to `(signal ...)`.

The current code (in master) is using `(signal ...)` as before, but now there's an extra `(define-error ...)` to let Emacs know that the symbol we give to `(signal ...)` is a subtype of `error` in the hierarchy of error types.
