### ISSUE TITLE
Prettier depends on the file extension to differentiate TypeScript and TSX

### ISSUE THREAD

**Issue by sangaline** [lassik/emacs-format-all-the-code#148]
When formatting either `.ts` or `.tsx`, prettier is getting invoked with the `--parser typescript` argument. This is the correct parser for both filetypes, but prettier additionally customizes the formatting based on the file extension and that information is lost when piping the file through stdin. This is a significant issue when working with TSX because a generic function written like

```tsx
const f = <T, >() => 1;
```

will be reformatted to

```typescript
const f = <T>() => 1;
```

and the latter is not valid TSX. The extra comma in the first version is the conventional workaround for handling generics in TSX files, and it's unusable with the current prettier behavior. You can find more details about this at prettier/prettier#6115.

Prettier supports a `--stdin-filepath` argument that would allow the file extension to be differentiated without needing to write a temporary file to disk. If this argument could be added with the path of the file when prettier is invoked, then I think it would resolve this issue.

**Comment by lassik** [comment]
format-all already passes `--stdin-filepath` to prettier. Did you try setting `format-all-debug` to `t` and looking in the `*Messages*` buffer for what command line format-all is using?

**Comment by sangaline** [comment]
Yeah, it outputs

```
Format-All: Running: /project/node_modules/.bin/prettier --parser typescript
Format-All: Directory: /project/src/components/
Already formatted
```

and I don't see any references to the `--stdin-filepath` argument. I just checked in `format-all--format-table` and I do see the code where it should be added:

```emacs-lisp
prettier
(closure
 (t)
 (executable mode-result)
 (ignore mode-result)

     ((parser mode-result))
   (format-all--buffer-easy executable
                            (if parser
                                (progn
                                  (list "--parser" parser)))
                            (if
                                (buffer-file-name)
                                (progn
                                  (list "--stdin-filepath"
                                        (buffer-file-name)))))))
```

The buffer does have a file name, and if I run `(buffer-file-name)` manually I see it with the correct TSX extension.

**Comment by lassik** [comment]
The [code is here](https://github.com/lassik/emacs-format-all-the-code/blob/b18ed67a81b4d81d77f3bd7cf6e004e4e412b630/format-all.el#L918). Do you have the latest version (most people install it from MELPA)?

**Comment by sangaline** [comment]
No, I just realized that my version is fairly out of date (pinned to 47d862d40). Sorry, I think this is a downstream issue with customizations that doom-emacs applies.
