### ISSUE TITLE
format-all is Broken After Upgrading Dependency language-id to 0.16

### ISSUE THREAD

**Issue by drcxd** [lassik/emacs-format-all-the-code#155]
I am currently using language-id 0.16 and format-all 0.50.

However, when I execute command `format-all-buffer` in a buffer whose major mode is `C++`, i.e. when I am editing a .cpp file, I get an error message in the echo area `No supported formatters for Cuda`.

**Comment by lassik** [comment]
Thanks for reporting this. Sorry about the bug. Fixed in https://github.com/lassik/emacs-language-id/pull/11
