### ISSUE TITLE
Standardrb formatter should include “—stderr” option in command

### ISSUE THREAD

**Issue by fapapa** [lassik/emacs-format-all-the-code#156]
The standardrb formatter should include the `—stderr` option in the issued command. Without this, the output from the command includes a line of repeating “=“ signs at the top of the output, which then ends up being included at the top of the file.

**Comment by lassik** [comment]
Thanks, it sounds like you're right. Could you send a pull request? The flag should be added [here](https://github.com/lassik/emacs-format-all-the-code/blob/06d4d9ee6dd79941d26798cc9754b9c9be87e932/format-all.el#L1141).

**Comment by fapapa** [comment]
Does the trick for me!

**Comment by lassik** [comment]
Great. Now in `master`.
