### ISSUE TITLE
HTML: Tidy enforces weird rules

### ISSUE THREAD

**Issue by HaoZeke** [lassik/emacs-format-all-the-code#16]
The problem is that `tidy` randomly enforces `<html>` and `<body>` tags with `.html` files.

If I haven't explicitly put those tags it's cuz I really don't need them (partials to be included elsewhere).

There are command line workarounds, but none of them are very neat and I'm not sure how to go about passing them through emacs.

**Comment by lassik** [comment]
I think `tidy` is supposed to work like that, always outputting complete HTML pages that conform to a DTD (doctype). Does it have options to suppress that, or do the workarounds involve manually taking out the `<html>` and `<body>` tags from its output?

One possibility would be to make a hook (`format-all-after-format-hook`) so people could add their own Emacs Lisp function to edit the buffer contents after formatting. It could take the formatter name as an argument so you could write a hook to only edit the output of `tidy` but not other formatters.

**Comment by HaoZeke** [comment]
`tidy --show-body-only yes -i 4 -w 80 -m file.html`

But then it doesn't fix any broken markup.


Another option would be to simply use [html-beautify](https://www.cleancss.com/html-beautify/)

**Comment by lassik** [comment]
Done in commit 8dedfb3. `(add-hook 'format-all-after-format-functions (lambda (formatter status) ...))` See the documentation for `format-all-after-format-functions'.
