### ISSUE TITLE
Specifying format-all-formatters does not seem to have an effect

### ISSUE THREAD

**Issue by SkyLeite** [lassik/emacs-format-all-the-code#161]
I am trying to get format-all-mode to use `rubocop` for my project. I have created the following `.dir-locals.el` file:

```
((nil
  (format-all-formatters
   ("Ruby" rubocop))))
```

I have also confirmed that `format-all-formatters` is set to what I expect in a Ruby file:
```
format-all-formatters is a variable without a source file.

Value in #<buffer company.rb>
(("Ruby" rubocop))
```

However, when running `format-all-buffer`, I get a message telling me `rufo` is not installed:
```
helm-M-x-execute-command: You need the "rufo" command. You may be able to install it via "gem install rufo".
```

What could be causing this? Feel free to ask for more information if it is needed.

**Comment by lassik** [comment]
Nothing is obviously wrong. Are you running Doom Emacs? Most mysterious bug reports come from Doom users :)

**Comment by SkyLeite** [comment]
Bingo. I'm using Doom Emacs (and I have `+format-with-lsp` set to `nil`)

**Comment by lassik** [comment]
That explains. Unfortunately, I can't help with Doom since I don't use it and they modified the behavior or format-all quite a bit. Please ask in their issue tracker; they can probably help.

**Comment by SkyLeite** [comment]
Thank you. I'll ask and re-open this if/when I have an answer.
