### ISSUE TITLE
Installation with straight fails due to inheritenv

### ISSUE THREAD

**Issue by nettoyoussef** [lassik/emacs-format-all-the-code#165]
I have a basic installation using the use-package version of straight:

```lisp
(use-package format-all 
  :demand
  :straight (format-all :host github
                      :repo "lassik/emacs-format-all-the-code")
  :hook
  (
   (ess-r-mode . format-all-mode)
   (python-mode . format-all-mode)
   )
)
```

However, I get an error related to the recipe of inheritenv:

```
helm-M-x-execute-command: Could not find package inheritenv. Updating recipe repositories: (org-elpa melpa gnu-elpa-mirror el-get emacsmirror-mirror) with ‘straight-pull-recipe-repositories’ may fix this
```

If I try to install inheritenv directly with `straight-use-package`, I get:

```
helm-M-x-execute-command: Recipe for inheritenv is malformed
```

Any idea on how I could solve that problem?

**Comment by raxod502** [comment]
I don't think anything is wrong with format-all here; it works for me. Try updating straight.el and your recipe repositories to the latest version, and if it's still broken, file an issue against straight.el.

**Comment by nettoyoussef** [comment]
Thank you both @lassik and @raxod502.
The issue was with the Melpa version I was using on my configuration file for straight.
By updating the commit hash on the melpa repository all was fine.
