### ISSUE TITLE
How to use prettierd instead of prettier?

### ISSUE THREAD

**Issue by shubham-cpp** [lassik/emacs-format-all-the-code#176]
[prettierd](https://github.com/fsouza/prettierd) is a faster implementation of prettier.
How could I use prettierd instead of prettier.

**Comment by shubham-cpp** [comment]
```elisp
  (define-format-all-formatter prettierd
    (:executable "prettierd")
    (:install "npm install --global @fsouza/prettierd")
    (:languages
    "CSS" "HTML" "JavaScript" "JSON" "JSON5" "JSX" "Less" "Markdown" "PHP" "SCSS" "TSX" "TypeScript" "YAML")
    (:features)
    (:format (format-all--buffer-easy executable (or (buffer-file-name) (buffer-name)))))
  (add-hook 'prog-mode-hook #'format-all-ensure-formatter)
  (add-hook 'json-mode-hook #'(lambda ()
                                (setq-local format-all-formatters '(("JSON" prettierd)
								    ("JSON5" prettierd)))))
  (add-hook 'web-mode-hook #'(lambda ()
                               (setq-local format-all-formatters '(("HTML" prettierd)
								   ("CSS" prettierd)
								   ("Less" prettierd)
								   ("SCSS" prettierd)))))


```

**Comment by lassik** [comment]
Great. Can you (or someone else) send a PR so `prettierd` is supported out of the box?

**Comment by Mo8it** [comment]
@lassik An implementation would be awesome. Can you please reopen the issue for that? Thanks! :)

**Comment by shubham-cpp** [comment]
Hi @lassik. I'll create a PR, but I want to inform that prettied isn't fully compatible with prettier. Prettierd  supports almost all the filetypes that prettier support, but there might be few issues like [this](https://github.com/fsouza/prettierd/issues/326).
For that, we would need to run `prettierd restart` from console
