### ISSUE TITLE
Comment out some lines in a c preprocessor (cpp) file will cause the comment section not to be left-aligned.

### ISSUE THREAD

**Issue by hongyi-zhao** [lassik/emacs-format-all-the-code#178]
On Ubuntu 20.04.3 LTS, I installed the git master version of format-all as follows:

```emacs-lisp
(use-package format-all
  :hook (format-all-mode . format-all-ensure-formatter)
  (prog-mode . format-all-mode)
  :config
  (setq format-all-show-errors 'errors)
  )
```

Then I opened the following `test.cpp` (c preprocessor) file in Emacs:

```c
$ gcc -E ifdef.cxx
# 1 "ifdef.cxx"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "ifdef.cxx"


#if 0
int i = 1;
#else
int i = 2;
#endif
```

When I try to comment out the following part in the above file with `M-;`:

```shell
$ gcc -E ifdef.cxx
# 1 "ifdef.cxx"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "ifdef.cxx"
```
I found that this file will be formatted into the layout below:

![image](https://user-images.githubusercontent.com/11155854/159612877-c3bdf485-e9ee-45f6-9715-abb707078d14.png)

As you can see, commenting out some lines in the above file will cause the comment section not to be left-aligned. I am very confused about this behavior triggered by `format-all`. Any hints will be appreciated.

See [here](https://lists.gnu.org/archive/html/help-gnu-emacs/2022-03/msg00407.html) for a related discussion.

Regards,
HZ

**Comment by lassik** [comment]
I don't have any obvious solutions. What formatter are you using -- `clang-format` or `astyle`? I tried both, and I don't get the indentation problem you get.

**Comment by hongyi-zhao** [comment]
> What formatter are you using -- `clang-format` or `astyle`?

I only use the default settings.  How to check the loaded formatters?
