### ISSUE TITLE
Can't deal with bash?

### ISSUE THREAD

**Issue by laishulu** [lassik/emacs-format-all-the-code#18]
I am editing a `foo.bash` file with `#!/usr/bin/env bash`.
emacs already show its in `sh[bash]` mode.
but:

```
Failed to format buffer due to errors
Formatter error output:
<standard input>:3:40: arrays are a bash feature

Failed to format buffer due to errors
```
while line#3 is:
```
root_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)
```

**Comment by lassik** [comment]
Interesting. Can you send the output of the following shell commands?

    shfmt -version
    echo '${BASH_SOURCE[0]}' | shfmt
    echo '${BASH_SOURCE[0]}' | shfmt -ln bash

On my computer, `shfmt -version` is `v2.5.1`

**Comment by lassik** [comment]
In your situation, format-all should give the command line flag `-ln bash` to shfmt to say that it's a bash script, so something is clearly going wrong here.

**Comment by laishulu** [comment]
![default](https://user-images.githubusercontent.com/1224321/47739380-3537bc00-dcb0-11e8-8f1c-7e41f3fa6b49.png)
maybe `bash` is not passed to shfmt?

**Comment by lassik** [comment]
OK, that's exactly the output I get as well. That does indeed seem to be the only option.  I don't know how much Emacs Lisp you know, but the relevant code in format-all is like this:

```
(format-all-buffer-easy
    executable
    "-ln" (cl-case (and (boundp 'sh-shell) (symbol-value 'sh-shell))
            (bash "bash")
            (mksh "mksh")
            (t "posix")))
```

So it tries to look at the value of `sh-shell` in the buffer being formatted.

**Comment by laishulu** [comment]
![default](https://user-images.githubusercontent.com/1224321/47857807-8ddc9580-de25-11e8-9858-ed917d62912d.png)

Is it because `bash` is not `'bash'`?

**Comment by lassik** [comment]
That look all right as well.

**Comment by lassik** [comment]
Do you have the latest version of format-all? The version number can be seen in `M-x list-packages`. I don't think any relevant changes have been made to new versions, but I can't think of anything else...

**Comment by laishulu** [comment]
![default](https://user-images.githubusercontent.com/1224321/47861005-c633a200-de2c-11e8-9de5-962e2276bb5f.png)

**Comment by laishulu** [comment]
weird, can't find `format-all` in list-packages.
though I can find in local dir.
I am using https://github.com/hlissner/doom-emacs

![default](https://user-images.githubusercontent.com/1224321/47861662-34c52f80-de2e-11e8-89d3-056b9d58694d.png)

**Comment by laishulu** [comment]
![default](https://user-images.githubusercontent.com/1224321/47862037-2fb4b000-de2f-11e8-81aa-c490a999c62d.png)

**Comment by lassik** [comment]
OK, I don't know anything about Doom Emacs. Thanks for communicating the bug to them :)

**Comment by laishulu** [comment]
The codes about format in doom-emacs is not too much. But I am a newbie to emacs migrating from vim, I can't check the codes to figure out the problems.

**Comment by lassik** [comment]
That's cool, welcome :) No problem.

I checked the doom-emacs source code and the `modules/editor/format` directory doesn't seem to be in the main repo. In fact, I can't find the whole `modules/editor` directory there at all. Is it a separate module?

**Comment by laishulu** [comment]
I use the develop branch which is the recommanded one. I guess you are checking the master branch?

**Comment by lassik** [comment]
Thanks. I didn't realize to look there. It seems they made a custom fork of the entire format-all package with lots of custom changes. I'll open a separate issue about that.

**Comment by laishulu** [comment]
Any progress?

**Comment by laishulu** [comment]
oh, I see https://github.com/lassik/emacs-format-all-the-code/issues/19

**Comment by lassik** [comment]
Yeah, sorry about that. This problem seems to be only in the Doom Emacs fork of format-all. Unfortunately I can't help with it, as they made so many changes to the code that it's almost entirely different. I'll try to find a way to work together with them. Hope you'll find a solution to your problem, one way or another :)
