### ISSUE TITLE
Unable to format any `Dockerfile`s

### ISSUE THREAD

**Issue by hjpotter92** [lassik/emacs-format-all-the-code#188]
When trying to format `Dockerfile` using `dockfmt`, the following error gets thrown in `*format-all-errors*` buffer

> Please pass in Dockerfile(s)

Running `dockfmt fmt <file>` from terminal works without issues.

**Comment by lassik** [comment]
You probably have an old version of `dockfmt`. Stdin support was added [in this PR](https://github.com/jessfraz/dockfmt/pull/8).

**Comment by hjpotter92** [comment]
Thanks. I was using the aur bundled one (https://aur.archlinux.org/packages/dockfmt). switching to git build resolved this.
