### ISSUE TITLE
Using diminish to suppress FmtAll from modeline. 

### ISSUE THREAD

**Issue by sdban** [lassik/emacs-format-all-the-code#191]
*This is a very minor issue.* 

Format-all shows up as `FmtAll` in the modeline. I wanted to suppress it using `diminish`.  

In `use-package` , I tried `:diminish format-all-mode`. 
But this seems to cause an error in the init-file. 

I am wondering if there is a way to get around it.

**Comment by lassik** [comment]
What's the error? Try `emacs --debug-init`

There shouldn't be anything special about `format-all-mode`. It's a typical minor mode.
