### ISSUE TITLE
Auto-close *format-all-errors* buffer on success

### ISSUE THREAD

**Issue by terlar** [lassik/emacs-format-all-the-code#21]
The buffer `*format-all-errors*` will pop-up as soon as there are some errors during the formatting. However, if you fix the errors and the formatting is successful the buffer still remains. I suggest closing the buffer if the formatting was successful. What do you think about this? Perhaps at least provide a `defcustom` for this if it is not a wanted default behavior.

**Comment by lassik** [comment]
You're right. I agree that the buffer should be closed if there are no errors. Just never got around to implementing that.

Do you happen to know what would be the appropriate Elisp functions to call to show and hide the error buffer? Currently I just call `display-buffer` to show it. I think there are some speciality functions that are a better fit for these tasks, but I never figured those out.

**Comment by terlar** [comment]
I think this snippet should work:
```
(save-selected-window (quit-window nil (get-buffer-window "*format-all-errors*")))
```

That is basically what they do in flycheck:
https://github.com/flycheck/flycheck/blob/master/flycheck.el#L4553-L4563

**Comment by lassik** [comment]
Thanks for investigating that :) Should be working now.

**Comment by terlar** [comment]
Thank you for the quick fix. It works very well now. Thank you for a great package 👍

**Comment by ndwarshuis** [comment]
this behavior seems to have changed with https://github.com/lassik/emacs-format-all-the-code/pull/232. Is there any way to auto-kill the window when errors are fixed?

**Comment by ndwarshuis** [comment]
@lassik thank you, that works :)
