### ISSUE TITLE
Why does ormolu config not have --stdin-input-file like fourmolu?

### ISSUE THREAD

**Issue by maridonkers** [lassik/emacs-format-all-the-code#216]
```emacs-lisp
(define-format-all-formatter fourmolu
  (:executable "fourmolu")
  (:install "stack install fourmolu")
  (:languages "Haskell" "Literate Haskell")
  (:features)
  (:format (format-all--buffer-easy executable "--stdin-input-file" (buffer-file-name))))
```

But `ormolu` doesn't have the `--stdin-input-file` configuration (I think it needs it; see [tweag/ormolu/issues/942#issuecomment-1328113066](https://github.com/tweag/ormolu/issues/942#issuecomment-1328113066))

**Comment by lassik** [comment]
> why does ormolu config not have the --stdin-input-file, like fourmolu has?

The formatter definitions were probably sent by different people, and we just forgot to add the flag to ormolu. Can you add it, test that it works, and if it does, send a PR?

**Comment by maridonkers** [comment]
PR: [lassik/emacs-format-all-the-code/pull/217](https://github.com/lassik/emacs-format-all-the-code/pull/217)
