### ISSUE TITLE
Haskell formatter jumps to top of screen on save

### ISSUE THREAD

**Issue by jappeace** [lassik/emacs-format-all-the-code#23]
Makes using the format-all-mode tedious as I save quite often.

**Comment by lassik** [comment]
Recent versions of format-all shouldn't do that. Which version do you have? You can find it in the `M-x list-packages` listing. The latest version is `20181108.921`.

**Comment by jappeace** [comment]
I'm sorry I'm on 20180722: `/nix/store/l32k2mvyz1gb7cxfswi3f150plaiyvkv-emacs-format-all-20180722.159.drv`. I'll complain at the nix people to upgrade.

**Comment by lassik** [comment]
No problem, thanks for reporting the issue to them :) Nix sounds very cool. I've been keeping an eye on it but haven't yet used it myself. I didn't know they mirror individual Emacs packages. Are you talking about [emacsPackagesNg](https://nixos.org/nixos/manual/index.html#module-services-emacs-adding-packages)?
