### ISSUE TITLE
Question: Ktlint formatter messes up formatting build.gradle.kts files?

### ISSUE THREAD

**Issue by torgeir** [lassik/emacs-format-all-the-code#237]
Hi,

Thanks for a great package! I enjoy this every day as part of doom emacs.

The ktlint formatter seems to mess up formatting `build.gradle.kts` on my end, so I am writing here just to confirm if this is an issue for you too.

E.g. file

```kts
// build.gradle.kts
dependencies {
}
```

After formatting

```kts
20:45:25.882 [main] INFO com.pinterest.ktlint.cli.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
20:45:26.506 [main] WARN com.pinterest.ktlint.cli.internal.KtlintCommandLine - Can not parse input from <stdin> as Kotlin, due to error below:
    Not a valid Kotlin file (1:1 expecting a top level declaration)
Now, trying to read the input as Kotlin Script.
dependencies {
}
```

I have fixed this temporarily by preventing log output other than for error messages by the following.

```emacs-lisp
(define-format-all-formatter ktlint
    (:executable "ktlint")
    (:install (macos "brew install ktlint"))
    (:modes kotlin-mode)
    (:format (format-all--buffer-easy executable "--format" "-l" "error" "--stdin")))
```

This seems like more of an issue with ktlint than with this module per se, I just wanted to check if this is also how it fares on your end.

Best regards,
Torgeir

**Comment by lassik** [comment]
PR #213 is a workaround for this issue. Let's apply it until the upstream issue is fixed.

**Comment by torgeir** [comment]
Agreed. An upstream fix feels like the right thing.
