### ISSUE TITLE
Support local Prettier

### ISSUE THREAD

**Issue by jbharat** [lassik/emacs-format-all-the-code#25]
Format-all-the-code depends on global installation of prettier. But there are cases where a project is not using prettier. In that case if prettier is globally installed, it creates a lot of unnecessary formats and commits.

I had used the below code on my personal config before I moved to doom-emacs which uses format-all
```
(defun my/prettier-setup ()
  (let* ((root (locate-dominating-file
                (or (buffer-file-name) default-directory)
                "node_modules"))
         (prettier (and root
                      (expand-file-name "node_modules/.bin/prettier"
                                        root))))
    (when (and prettier (file-executable-p prettier))
      (prettier-js-mode t))))
```

Any way to make it use local prettier instead of globally installed prettier?

**Comment by lassik** [comment]
Thanks for asking :) format-all finds all formatters using `executable-find`:

 > Search for COMMAND in `exec-path' and return the absolute file name.

The value of `exec-path` comes from the `PATH` environment variable at Emacs startup but can be modified later using e.g. [exec-path-from-shell](https://melpa.org/#/exec-path-from-shell). If you put `node_modules/.bin/prettier` in `exec-path` before the directory of the global `prettier`, then format-all should use your project-local `prettier`. This answer on the Emacs StackExchange has more about it: [exec-path and $PATH](https://emacs.stackexchange.com/questions/550/exec-path-and-path).

Unfortunately, `exec-path` is normally a global variable. You can make buffer-local overrides to the global value by doing `(make-variable-buffer-local 'exec-path)` but I don't know if there are any gotchas to it. I'll ask on StackExchange. For using project-local formatters, I would favor some (preferably `exec-path`-based, if possible) approach that is shared by many or all Emacs packages. We had this same discussion about project-local path overrides in the GitHub issues of some other Emacs package. Would be nice to have a common way to solve the problem for everyone.

**Comment by lassik** [comment]
I missed this part:

> But there are cases where a project is **not using** prettier. In that case if prettier is globally installed, it creates a lot of unnecessary formats and commits.

For projects that are not using a formatter, you can simply turn off `format-all-mode` in those buffers (the mode is buffer-local, not global). This can be done by having an if-statement in the hook where you turn on format-all-mode. The help (docstring) for the `format-all-mode` function gives an example using `after-change-major-mode-hook`.

**Comment by jbharat** [comment]
As you suggested, I will try to disable format-all-code if prettier is not local. I think it should solve the problem. Thanks. This is not a bug anyway. I will close it.
