### ISSUE TITLE
Unable to format with `ruff`

### ISSUE THREAD

**Issue by chookity-pokk** [lassik/emacs-format-all-the-code#250]
I am trying to use `ruff` on a python file and I get the below error.

```
error: unexpected argument '--stdin-filename' found

  tip: to pass '--stdin-filename' as a value, use '-- --stdin-filename'

Usage: ruff format <--verbose|--quiet|--silent> [FILES]...

For more information, try '--help'.
```

I don't really know enough elisp to help here, sorry!

**Comment by doolio** [comment]
I can't reproduce this error. If I open an unformatted python file and `M-x format-all-buffer` I first see a list of formatters to choose from which I select `ruff` and then see the following messages. I'm not using any LSP client in this test.

```
Setting formatter to ruff
Reformatted!
```

Can you maybe detail the steps you follow that produces this error?

**Comment by chookity-pokk** [comment]
My steps are the same as yours. I also just uninstall ruff, closed emacs, reinstalled ruff (`0.1.11`), launched emacs again and got the same error. I have a different computer I can try this on and I'll see if it might be something going on with my laptop.

**Comment by doolio** [comment]
Yes, another data point could help. We are using the same version of `ruff`. I'm still using Emacs 27.1 though. You never said but I assume you see this error in the \*Messages\* buffer?

**Comment by chookity-pokk** [comment]
I got it working on my other computer. Same steps but this time ruff worked. So I am thinking it has to be an issue with MacOS or something. My work laptop is an M2 and the other laptop I tested with was running Arch. Both of which are running emacs 29.1.

> You see this error in *Messages* buffer?
No, it's in a *format-all-errors* buffer and *Messages* just shows "Formatting error"

**Comment by doolio** [comment]
No problem, glad you go it working on one machine at least.

**Comment by chookity-pokk** [comment]
I got it working on my Mac by using https://github.com/purcell/exec-path-from-shell with the setup

```
(package-install 'exec-path-from-shell)
(exec-path-from-shell-initialize)
```

**Comment by doolio** [comment]
Glad to heat it. Yes, `exec-path-from-shell` is by all accounts an essential package when working on a mac.
