### ISSUE TITLE
format-all-buffer fails with a "wrong number of arguments" error

### ISSUE THREAD

**Issue by JohnEmhoff** [lassik/emacs-format-all-the-code#26]
`M-x format-all-buffer` fails with the error `Wrong number of arguments: (0 . 1), 2`.

I have emacs 25.5.2 and format-all 20181207.2019; let me know if anything else will help to debug, or if I'm not using it as intended.

**Comment by lassik** [comment]
Thanks for the bug report. Please do `M-x set-variable debug-on-error t`. That is, set the value of the `debug-on-error` variable to `t` (the boolean value true). This should show a long error message with a stack trace when the error occurs. Please paste the stack trace (or the relevant parts of it).

**Comment by JohnEmhoff** [comment]
```
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 1) 2)
  line-number-at-pos(nil t)
  format-all-save-line-number(#[0 "..."])
  format-all-buffer()
  funcall-interactively(format-all-buffer)
  call-interactively(format-all-buffer record nil)
  command-execute(format-all-buffer record)
  execute-extended-command(nil "format-all-buffer" "format-all-buff")
  funcall-interactively(execute-extended-command nil "format-all-buffer" "format-all-buff")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

Looks like `line-number-at-pos` changed recently (emacs 26?) to accept two arguments; older versions like I have (25) still take only one :(

**Comment by JohnEmhoff** [comment]
Rock and/or roll; thanks!

**Comment by JohnEmhoff** [comment]
Looks great, thanks again!
