### ISSUE TITLE
Switch YAML from yq to prettier?

### ISSUE THREAD

**Issue by lassik** [lassik/emacs-format-all-the-code#39]
Prettier now has YAML support (`prettier --parser yaml`). The current formatter `yq` works but is probably not very popular. Should we switch to Prettier?

When the multi-formatter support finally gets going, we can have both of course.

**Comment by terlar** [comment]
I think this would be good, I haven't tried it prettier for YAML yet, but I have tried to use `yq` on a cloudformation template, but it ended up breaking it. Don't remember the exact details, but I think it was related to the `!Sub` functions and the like.

**Comment by lassik** [comment]
yq is using [mikefarah/yaml](https://github.com/mikefarah/yaml) as its YAML parser. The readme says: 

> The yaml package supports most of YAML 1.1 and 1.2, including support for anchors, tags, map merging, etc. Multi-document unmarshalling is not yet implemented, and base-60 floats from YAML 1.1 are purposefully not supported since they're a poor design and are gone in YAML 1.2.

**Comment by lassik** [comment]
Closed by #51. Preffier is now the YAML formatter.
