### ISSUE TITLE
Add reminder to exec path from shell

### ISSUE THREAD

**Issue by ianpan870102** [lassik/emacs-format-all-the-code#40]
In addition to installing the required external programs to format the buffer, one shouldn't forget to exec path from shell either! Other Emacs will not be able to use the programs installed for example under` /usr/local/bin/...`

Adding this reminder to README.md can save users from tracking down this problem!

The easiest way is probably to use this package from Purcell: https://github.com/purcell/exec-path-from-shell

**Comment by lassik** [comment]
Thanks for the suggestion. I created a PR #41 to add a note to the README. Does it look reasonable?

**Comment by lassik** [comment]
I also use exec-path-from-shell myself, and would recommend it :)

**Comment by lassik** [comment]
Closing this since the README update from pull request #41 is now in master. Feel free to re-open if you want to improve it.

**Comment by ianpan870102** [comment]
Brilliant @lassik! Thanks for the great work, I'm really enjoying this package and would recommend to anyone.

**Comment by ianpan870102** [comment]
Just one minor grammar mistake: "...You easily make it match your shell's `PATH` using..."
should be "...You **can** easily make it match your shell's `PATH` using..."

Have a nice day!

**Comment by lassik** [comment]
Well spotted. For some reason, I often drop words from sentences when editing.

Thanks for the kind words! Personally, I would characterize this kind work more as "plumbing" than brilliant :) A better cross-editor solution is long overdue. In any case, life with code formatters is so much easier than going without.

**Comment by lassik** [comment]
Kind _of_ work :D There we go again.
