### ISSUE TITLE
Use Standard instead of Prettier for Javascript?

### ISSUE THREAD

**Issue by ianpan870102** [lassik/emacs-format-all-the-code#44]
**Standard** JS (https://standardjs.com/index.html#why-should-i-use-javascript-standard-style) is a popular style / lint tool and is adopted by big players like **GitHub, NodeJS, npm, MongoDB, Brave browser, Express, Electron, Atom**....

IMO the philosophy of **Standard** also adheres more to your format-all package! Just like **black** for Python, Standard strives to have **zero**-configuration.

**Comment by lassik** [comment]
That's nice! Standard was actually the first supported JavaScript formatter but I substituted prettier which was faster and covered more languages.

At the time, I thought it would be best to focus on the most "standard" formatter for each language. But lots of people want the custom args anyway, and I thought of a simple way to support them, so I thought why not give people what they want :) We are also currently procrastinating and overcommitted on Unibeautify (which was intended to solve multiple formatters). Available time and morale for these formatter projects is not the greatest right now, but I hope it picks up again.

I believe lots of people are now using Prettier for JavaScript right now, so we should resolve the [multiple-formatters procrastination thread](https://github.com/lassik/emacs-format-all-the-code/issues/27) and then add support for Standard in addition to Prettier 😄

**Comment by ianpan870102** [comment]
I see, this makes sense. Having the ability to choose multiple formatters is indeed something many users look forward to. I'll keep myself updated! (Closing issue)

**Comment by ianpan870102** [comment]
P.s. Repost from my comment in #27 : 

> ...from directory-local variables, from hooks, or from anywhere else they prefer

I second this idea, this seems to be able to solve most people's needs. On top of that, I think it's reasonable to use mode-hooks as the first thing users set, then directory-local-variables is set with higher priority. The motivation behind this idea is for e.g. For all personal Python projects I want to use black, but only one specific project I want to use autopep8 because that's what my team went with. Then we would be able to hook general python-mode to formatting with black, and add this particular directory to be autopep8 formatted. Since you intended to support chaining, perhaps it would be nice to have the option to disable a formatter, so that one could choose between chaining autopep8 after black, or directly override black with autopep8 for a specific project.

> Should we continue to have default formatters?

Yes, definitely IMO!

**Comment by lassik** [comment]
If my understanding is correct, we can just provide a buffer-local variable that says what formatter(s) to use for that buffer. Users can set it from hooks and/or dir-local variables as they wish. But more on that in #27 :)
