### ISSUE TITLE
How to select formatter for define-derived-modes

### ISSUE THREAD

**Issue by ianpan870102** [lassik/emacs-format-all-the-code#45]
So I have **web-tsx, web-html, and web-css** all derived from **web-mode**. How can I configure a formatter for each of the modes? E.g. Prettier for web-tsx, Tidy for web-html, etc.

**Comment by lassik** [comment]
Good question. I didn't know about those derived modes. Are they available in a published package somewhere, or are they your own extensions of web-mode? If they are published, it should work if we just add them to format-all's mode lists. If they are private, I'll have to think a bit. But it'd definitely be good to support this somehow.

**Comment by ianpan870102** [comment]
They are all my self-derived modes, so it could be a little difficult compared to some published modes.

**Comment by lassik** [comment]
This could be combined with the formatter selection support (as discussed in the Custom Formatter Procrastination Thread, #27 - better to be honest about what it is :)

People should be able to easily switch between prettier and html-tidy anyway, even if they are using the published web-mode and html-mode, so it's good to get this fixed.

**Comment by ianpan870102** [comment]
Ah custom formatter would be a dream-come-true, I can imagine many users are dying for this feature haha!
