### ISSUE TITLE
change haskell format tool

### ISSUE THREAD

**Issue by Vonfry** [lassik/emacs-format-all-the-code#57]
use [stylish](https://github.com/jaspervdj/stylish-haskell) instead

**Comment by lassik** [comment]
Haskell seems to now have at least 3 formatters, each with its own fans. This would be a good case for the multi-formatter support.

**Comment by lassik** [comment]
This is now possible. Please follow issue #27 if still interested.

**Comment by lassik** [comment]
Multi-formatter support is now in master so we support all three Haskell formatters as alternatives:

* hindent
* brittany
* stylish

**Comment by lassik** [comment]
_can_ support, that is :) Just need to write the formatter definitions.

**Comment by lassik** [comment]
OK, now we have all three.

`hindent` worked before in format-all but I didn't test that it works again; I just copied the old definition.

`stylish-haskell` is brand new; also not tested, but should work according to the documentation.

Please say if any of these don't work and we'll fix it.
