### ISSUE TITLE
Elixir mix format ignores config in subdirectories

### ISSUE THREAD

**Issue by goofansu** [lassik/emacs-format-all-the-code#62]
This is caused by formatter not using the correct `.formatter.exs`. 

In `format-all`, `mix.exs` is used to locate the directory to run the formatter,  it just takes the `.formatter.exs` in the same directory instead of using the `.formatter.exs` that defined the pattern for the file to format.

https://github.com/lassik/emacs-format-all-the-code/blob/d522ffe256a97e7c4043afe5394b0be53c54b7cc/format-all.el#L548-L549

For example,

/srv/myapp/.formatter.exs
```elixir
[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  subdirectories: ["priv/subdir"]
]
```

/srv/myapp/priv/subdir/.formatter.exs
```elixir
[
  import_deps: [:ecto_sql],
  inputs: ["*.exs"]
]
```

After save file /srv/myapp/priv/subdir/create_users.exs
```elixir
defmodule MyApp.CreateUsers do
  def change do
    create unique_index(:users, :email)
  end
end
```

It becomes following while it should keep the old format.
```elixir
defmodule CreateUsers do
  def change do
    create(unique_index(:users, :email))
  end
end
```

**Comment by lassik** [comment]
Thanks for a clearly written bug report!

Unfortunately, we need to use stdin->stdout instead of formatting by filename - formatting by filename would cause more problems than it solves.

However, some formatters have a `--stdin-filename a/b/c.ext` flag that let you format stdin->stdout but act as if the contents of stdin came from a file with the given name. This affects where the formatter looks for its config file. Does `mix format` have such a flag?

Currently format-all looks for the first parent directory containing `mix.exs` and changes to that directory before running `mix format`. Would it help if we also looked for `.formatter.exs`?

**Comment by lassik** [comment]
I don't have `mix format` installed right now, but you can try this by changing `'("mix.exs")` into `'("mix.exs" ".formatter.exs")` and then `M-x load-file format-all.el`.

**Comment by goofansu** [comment]
@lassik Thanks for the reply

> However, some formatters have a --stdin-filename a/b/c.ext flag that let you format stdin->stdout but act as if the contents of stdin came from a file with the given name. This affects where the formatter looks for its config file. Does mix format have such a flag?

There is no such flag in `mix format` command.

```
## Task-specific options

  • --check-formatted - checks that the file is already formatted. This is
    useful in pre-commit hooks and CI scripts if you want to reject
    contributions with unformatted code. However keep in mind that the
    formatted output may differ between Elixir versions as improvements and
    fixes are applied to the formatter.
  • --check-equivalent - checks if the files after formatting have the same
    AST as before formatting. If the ASTs are not equivalent, it is a bug in
    the code formatter. This option is useful if you suspect you have ran into
    a formatter bug and you would like confirmation.
  • --dry-run - does not save files after formatting.
  • --dot-formatter - path to the file with formatter configuration.
    Defaults to .formatter.exs if one is available. See the ".formatter.exs"
    section for more information.
```

> Would it help if we also looked for .formatter.exs?

No. Because there is `import_deps`, according to following document, `mix format` must run in the directory that defines the deps, so it cannot run in a subdirectory with only `.formatter.exs`.

```
   • :import_deps (a list of dependencies as atoms) - specifies a list of
    dependencies whose formatter configuration will be imported. When
    specified, the formatter should run in the same directory as the mix.exs
    file that defines those dependencies. See the "Importing dependencies
    configuration" section below for more information.
```

**Comment by goofansu** [comment]
@lassik You can see when `mix format -`, it will not use the `.formatter.exs` in `priv/subdir/`.

```
$ mix format -
args: [
  stdin: [
    inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
    subdirectories: ["priv/subdir"]
  ]
]
defmodule CreateUsers do
  def change do
    create(unique_index(:users, :email))
  end
end
defmodule CreateUsers do
  def change do
    create(unique_index(:users, :email))
  end
end


$ mix format priv/subdir/create_users.exs
args: [
  {"/Users/james/src/elixir_formatter_playground/priv/subdir/create_users.exs",
   [
     import_deps: [:ecto_sql],
     inputs: ["*.exs"],
     locals_without_parens: [
       add: 2,
       add: 3,
       alter: 2,
       create: 1,
       create: 2,
       create_if_not_exists: 1,
       create_if_not_exists: 2,
       drop: 1,
       drop_if_exists: 1,
       execute: 1,
       execute: 2,
       modify: 2,
       modify: 3,
       remove: 1,
       remove: 2,
       remove: 3,
       rename: 2,
       rename: 3,
       timestamps: 1
     ]
   ]}
]

```

**Comment by goofansu** [comment]
@lassik I found we can locate the closest `.formatter.exs` for the file to format. Then run `mix format --dot-formatter THE_CLOSESET_FORMATTER_EXS -`.

```
$ mix format --dot-formatter priv/subdir/.formatter.exs -
defmodule CreateUsers do
  def change do
    create unique_index(:users, :email)
  end
end
defmodule CreateUsers do
  def change do
    create unique_index(:users, :email)
  end
end
```

**Comment by goofansu** [comment]
@lassik PR created #63
