### ISSUE TITLE
can't auto-format protobuf source code

### ISSUE THREAD

**Issue by Jackson-soft** [lassik/emacs-format-all-the-code#75]
(use-package format-all
  :diminish
  :hook (prog-mode . format-all-mode))

**Comment by lassik** [comment]
Which operating system are you running, and what is the output of the following Emacs command?

`M-x` `shell-command` `clang-format --version`

Can you also try:

* `M-x` `eval-expression` `(setq format-all-debug t)` (enable format-all debug mode)
* `M-x` `protobuf-mode` (make sure the file you are editing is in Protocol Buffers mode)
* `M-x` `format-all-buffer` (run format-all on the file)

In debug mode, format-all writes a few diagnostic messages to the end of the Emacs buffer named `*Messages*` every time you format a buffer (they are also displayed on the status line one by one). I just tried to format a Protocol Buffers file - it works and I get the following in `*Messages*`:

```
Format-All: Formatting example.proto using (clang-format ".proto")
Format-All: Running: /usr/local/bin/clang-format -assume-filename\=/tmp/example.proto
Format-All: Directory: /tmp/
Reformatted!
```

**Comment by Jackson-soft** [comment]
format-all-buffer can work,but can't auto-format

**Comment by lassik** [comment]
Aha, `protobuf-mode` is not derived from `prog-mode`. You need to add a separate hook for `protobuf-mode`.

**Comment by Jackson-soft** [comment]
Yeah, I found that, too. Thank you
