### ISSUE TITLE
Formatting Ruby with Prettier

### ISSUE THREAD

**Issue by raymondboswel** [lassik/emacs-format-all-the-code#79]
Greetings and thank you for the good work :)

Our team uses prettier to format ruby; I've hacked my local copy of the format all code to add Ruby to the list of prettier languages, though I'm sure there must be a better and more persistent way to accomplish this. Any ideas?

**Comment by lassik** [comment]
Thanks for the kind words!

So far, format-all has only been able to support one formatter per language. Our formatter of choice for Ruby was `rufo` which is quite reliable and has good defaults. A moment ago, I finally committed multi-formatter and custom-args support into the `multi-formatter` branch. With multi-formatter support, we can add any number of alternative formatters for the same language, so adding support for prettier's Ruby plugin is not a problem anymore.

Please check the end of issue #27 and the `multi-formatter` branch. You should be able to enable Prettier's Ruby support simply by adding `"Ruby"` to the `:languages` list in format-all's prettier definition.

**Comment by lassik** [comment]
Once we've ironed out the problems from the multi-formatter support, I'll push it to MELPA for everyone to use so you don't need to have a customized copy of format-all.

**Comment by raymondboswel** [comment]
Great stuff! It looks like my timing for wanting this feature is pretty good :) I'll check out the branch later today and give it a try. Thanks!
