### ISSUE TITLE
Missing mode with existing support

### ISSUE THREAD

**Issue by ztlevi** [lassik/emacs-format-all-the-code#8]
`gfm-mode` and a sub-mode of `markdown-mode`, `typescript-tsx-mode` is a mix of typescript and jsx. Also `js3-mode`, I don't know how many ppl use it, but it's better to just add it.

Prettier already have those parsers ready. These modes need to be added.

**Comment by lassik** [comment]
Thanks! Which MELPA packages can I install to test these modes?

**Comment by ztlevi** [comment]
`gfm-mode` comes with `markdown-mode`. `js3-mode` is stand alone. `typescript-tsx-mode` is a tweak. It derived from `web-mode` and it's a tweak from [Spacemacs](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/typescript/packages.el#L94).

**Comment by lassik** [comment]
Thanks :) All of them should work now (but I only managed to test `js3-mode`, not the others).

**Comment by lassik** [comment]
I presume this is working. Please re-open if not :)
