### ISSUE TITLE
Can you support another formatting tool for cmake?

### ISSUE THREAD

**Issue by Jackson-soft** [lassik/emacs-format-all-the-code#80]
[Lsp-mode](https://github.com/emacs-lsp/lsp-mode) is currently using a language server.

[cmake-language-server](https://github.com/regen100/cmake-language-server)

**Comment by lassik** [comment]
OK, pending this: https://github.com/regen100/cmake-language-server/issues/4

**Comment by lassik** [comment]
Even though it's a LSP server, they also have a `cmake-format` CLI command. But we'd need stdin support for it.

**Comment by Jackson-soft** [comment]
thanks
