### ISSUE TITLE
disable using .dir-locals.el

### ISSUE THREAD

**Issue by showgood** [lassik/emacs-format-all-the-code#82]
Sometimes I need to disable format-all-code mode for certain directories, I have tried using `.dir-locals.el` but without success.

Can this be supported? If it's already supported, how can I achieve what I want?

Thanks!

**Comment by lassik** [comment]
If you're enabling format-all in `after-change-major-mode-hook`, that hook is probably run after `.dir-locals.el` has been read. That means the hook will override decisions made by `.dir-locals.el`.

Are you using format-all from MELPA? The `multi-formatter` branch has multi-formatter and custom-args support that's not yet in MELPA. Issue #27 explains the details. I've been using that branch for a few weeks and have had no issues with it, so I should probably push it into MELPA but nobody else has given me any feedback on it yet.

The branch makes it so you need to either set `format-all-formatters` (in a hook, or in `.dir-locals.el`) or do `M-x format-all-buffer` manually in order for format-all to format a buffer at all. If you don't do one of those things, then `format-all-mode` will not format your buffer on save.

`format-all-mode` is currently a buffer-local mode. It might make sense to change it into a global mode. So it would be always on, but only buffers with `format-all-formatters` set or `M-x format-all-buffer` done would get formatted. What do you think about such an approach?

**Comment by showgood** [comment]
I have tried the branch with `.dir-locals.el` and it works!

I am personally happy with the `dir-locals.el` approach. thanks for the help!

**Comment by lassik** [comment]
Thanks for being the first to give feedback on it :) I'll try to find time to polish it a bit push it to MELPA sometime in the next week.
