### ISSUE TITLE
Support snakemake

### ISSUE THREAD

**Issue by alienzj** [lassik/emacs-format-all-the-code#86]
Hi, 
Emacs support snakemake by using https://github.com/kyleam/snakemake-mode.
Could we use https://github.com/snakemake/snakefmt to format snakemake code?

**Comment by lassik** [comment]
Yes, it should work. `snakefmt -` formats code from stdin to stdout; that's what format-all needs.

**Comment by lassik** [comment]
What's the easiest way to install `snakefmt`? Is there something easier than `git clone` and `poetry`?

**Comment by alienzj** [comment]
There no conda package for `snakefmt`.

**Comment by lassik** [comment]
Done. It shows `[INFO] Formatting from stdin` every time you format a file. I can't find an option in `snakefmt` to hide that message; the snakefmt authors would have to either drop that message or add a `-q` (quiet) flag to hide it.

**Comment by lassik** [comment]
Closing this issue since the formatter would appear to work. Feel free to re-open it if there are problems.

If you want to get rid of the `[INFO]` text, please ask the snakefmt authors to support it. If it requires a command line flag to hide the message, we can tell format-all to use that flag.
