### ISSUE TITLE
Use cargo fmt, not rustfmt

### ISSUE THREAD

**Issue by billop** [lassik/emacs-format-all-the-code#87]
Currently format-all will raise errors on any rust code that is on the 2018 edition. Swapping out rustfmt for cargo fmt would solve this, and probably other issues that arise from cargo fmt passing various options to rustfmt based on the cargo.toml.

**Comment by lassik** [comment]
Thanks for reporting this. Is `cargo fmt` a drop-in replacement for `rustfmt` for Rust code using other editions as well?

**Comment by lassik** [comment]
There is now multi-formatter support (working, but still to be merged into the master branch) so in principle we can still keep direct `rustfmt` support around if it's useful in some scenarios.

**Comment by billop** [comment]
`cargo fmt` calls `rustfmt`, so it's more of a thin wrapper that takes into account project settings stored in `cargo.toml`. I propose that it be the default so that format-all works out of the box for most use cases. I can't really imagine a case where `rustfmt` would be preferred. I don't know of anyone not using `cargo` for their Rust projects.

**Comment by lassik** [comment]
I haven't heard of any Rust projects not using cargo either. Your rationale is convincing - let's make the change.

* What's the precise `cargo fmt` command to format code from stdin to stdout?

* Does the command need to be run from the directory containing `cargo.toml´, or can it be run from any subdirectory?

**Comment by billop** [comment]
Since pretty much every rust project uses cargo, I believe we can also assume that everyone has a `Cargo.toml` and standard project directory setup (e.g. `src/`, `target/`, etc.). This means that I think we should assume that when `format-all-buffer` on a rust file, we can assume that `cargo fmt` will find the `cargo.toml` by itself since the file path will almost always be within the project directory.

Here is the help of `cargo fmt` for reference:
```
cargo-fmt 1.4.11
This utility formats all bin and lib files of the current crate using rustfmt.

USAGE:
    cargo fmt [FLAGS] [OPTIONS] [-- <rustfmt-options>...]

FLAGS:
        --all        Format all packages (only usable in workspaces)
    -h, --help       Prints help information
    -q, --quiet      No output printed to stdout
    -v, --verbose    Use verbose output
        --version    Print rustfmt version and exit

OPTIONS:
        --manifest-path <manifest-path>      Specify path to Cargo.toml
        --message-format <message-format>    Specify message-format: short|json|human
    -p, --package <package>...               Specify package to format (only usable in workspaces)

ARGS:
    <rustfmt-options>...    Options passed to rustfmt
```

I think all that's needed really is `cargo fmt -- --emit stdout <current buffer's path>` in order to take the file path, and get stdout of the formatted contents.

**Comment by lassik** [comment]
@billop Sorry, I missed your last comment for some reason and neglected to implement this.

Thanks to @sondr3 for getting to it. The PR is now merged and MELPA should pick it up in about an hour. I don't actively use Rust myself, so please let me know if you encounter any problems.
