### ISSUE TITLE
bash script formatting error

### ISSUE THREAD

**Issue by haoyuan80s** [lassik/emacs-format-all-the-code#89]
Hi,
I have a bash script:
```
#!/bin/bash

strings=(a b    c)
```
After running `format-all-buffer`, it shows error:
`<standard input>:3:9: arrays are a bash/mksh feature`

Is the because I am using a zsh shell? But, I can format is the shell by `shfmt tmp.sh`, which output
```
#!/bin/bash

strings=(a b c)
```
How to fix the error?

**Comment by haoyuan80s** [comment]
Yes, shell type is the problem. `export SHELL=/bin/bash; emacs` fix the error.

**Comment by lassik** [comment]
If you open a file that does not have `#!/bin/bash` and then add it, sh-mode will not automatically realize that you changed the shell to bash. Doing `M-x normal-mode` should fix that. A more manual way to do it is `M-x sh-set-shell bash`.

**Comment by lassik** [comment]
`M-x normal-mode` is like a "reset" button for the settings: Emacs does all the auto-detection it would do when opening the file. Works for all kinds of files, not just shell scripts.
