### ISSUE TITLE
`shfmt` ignores config file

### ISSUE THREAD

**Issue by haoyuan80s** [lassik/emacs-format-all-the-code#90]
To config shfmt style, I added `.editorconfig` in the same folder of a `foo.sh` file. When running command line `shfmt foo.sh`, the output follows the style defined in `.editorconfig`. However, the `format-all-buffer` command ignores the style config file.

-----
foo.sh (four spaces indentation)
```
f() {
    echo hello
}
```
content of `.editorconfig`
```
[*.sh]
indent_style = space
indent_size = 2
```

output of `shfmt foo.sh` (two spaces)
```
f() {
  echo hello
}
```

after `M-x format-all-buffer` (eight spaces)
```
f() {
	echo hello
}
```

**Comment by lassik** [comment]
Thanks for reporting the bug. If you do `shfmt < foo.sh` in the shell (note the `<` sign) how many spaces does it use?

**Comment by lassik** [comment]
Aha. It's probably because you have a `[*.sh]` filename pattern in your `.editorconfig`. Format-all runs all formatters so that they read from stdin and write to stdout, so it does not give shfmt a filename. Then shfmt doesn't know that it should use the `[*.sh]` section of the config.

**Comment by lassik** [comment]
In order to fix this problem in format-all, a new command line flag needs to be added to shfmt. I sent them a feature request about it.

**Comment by lassik** [comment]
shfmt's maintainer was kind enough to add a `-filename` flag! I'll wait for a new shfmt release and then fix this problem in format-all.

**Comment by haoyuan80s** [comment]
Looking forward to this feature, thanks!

**Comment by jsmestad** [comment]
Also eagerly anticipating this feature!

**Comment by lassik** [comment]
The `-filename` flag is still not in the latest release 3.1.2. It looks like a 3.2.0 release is just around the corner: https://github.com/mvdan/sh/milestone/18
