### ISSUE TITLE
run format-all-buffer in rust mode will clear this buffer

### ISSUE THREAD

**Issue by Iorest** [lassik/emacs-format-all-the-code#91]
However， it works well in terminal like `cargo fmt`,`rustfmt`.

**Comment by lassik** [comment]
Thanks for reporting the bug - sounds pretty severe. Are there any error messages in the `*format-all-errors*` buffer?

**Comment by Iorest** [comment]
No，there is nothing in the `*format-all-errors*` ,the only problem is this command clears the buffer in
 rust mode.

**Comment by lassik** [comment]
If you do `cargo-fmt < some-file.rs` from the terminal (note the ´<`), what happens - does it write out the reformatted code to standard output? Does `echo $?` (i.e. exit status of last command) show `0` (i.e. success)?

**Comment by Iorest** [comment]
I run `cargo-fmt < some-file.rs` from the terminal,it write nothing

![image](https://user-images.githubusercontent.com/16451699/85292519-9ab46e00-b4ce-11ea-828c-3b0d4fa1e8fb.png)

**Comment by lassik** [comment]
Interesting. I did `rustup` in a Docker container and managed to replicate your situation. It seems `cargo-fmt` needs to be told to `--emit stdout` in order to format code from stdin to stdout (format-all needs to do it that way).

I pushed a commit to master to try and fix it. (Should also be in MELPA in 1-2 hours.) Does it solve your problem?

**Comment by Iorest** [comment]
It can write out now,but it will write out the directory at first line.

**Comment by lassik** [comment]
Wow, this is a lot more complicated than we thought when making the change from `rustfmt` to `cargo-fmt`.

OK, after more testing, this works: `cargo-fmt -- --quiet --emit stdout < foo.rs`

So just as before, but with an extra `--quiet` flag.

If you put some code with syntax errors into `foo.rs`, it writes the error messages to stderr as it should, and writes them even if `--quiet` is given, which is right for us.

**Comment by lassik** [comment]
Can you verify that it uses the right formatting settings (i.e. finds the right settings file) when formatting a `.rs` file that is in a subdirectory (nested directory) of a project?

**Comment by Iorest** [comment]
Yes，It works well now.Thanks for your work.

**Comment by lassik** [comment]
Glad to hear that it finally does :) Thanks for sticking with it.
