### ISSUE TITLE
can you add support SQL formatter pg_format?

### ISSUE THREAD

**Issue by Jackson-soft** [lassik/emacs-format-all-the-code#94]
https://github.com/darold/pgFormatter

**Comment by lassik** [comment]
Yes, should work fine! It can read from stdin and write to stdout.

What's the normal way to install it?

**Comment by lassik** [comment]
Sorry about the huge delay again. I've tried to recruit new maintainers but nobody has taken up the offer.

**Comment by Jackson-soft** [comment]
OK，Still thank you

**Comment by lassik** [comment]
Multi-formatter support was just merged into the `master` brahcn, so we should now be able to add this.

**Comment by lassik** [comment]
I made the formatter symbol `pg-format` (with dash) because Lisp uses dashes, even though the command-line command is `pg_format` (with an underscore instead). This is unfortunate; couldn't think of a better way to solve it.

**Comment by Jackson-soft** [comment]
You can refer to this：

https://github.com/purcell/sqlformat/

**Comment by lassik** [comment]
Thanks! I changed the symbol to `pgformatter` for consistency with Steve's package.
