### ISSUE TITLE
`cargo fmt` cannot be used for formatting a single rust buffer

### ISSUE THREAD

**Issue by jenanwise** [lassik/emacs-format-all-the-code#95]
In #87 / #88, the `rustfmt` formatter was switched from calling `rustfmt` directly to using `cargo fmt` so that it would respect `Cargo.toml`. Unfortunately, `cargo fmt` cannot format a single file. It will actually format _all_ the files in the crate. When combined with `--emit=stdout` ([as in current master](https://github.com/lassik/emacs-format-all-the-code/blob/5748764079e427109a0501fbeda79debacc52a9e/format-all.el#L641)), this will spit out all the crate's src into the current buffer on save.

See discussion in https://github.com/rust-lang/rustfmt/issues/4074

There doesn't appear to be a way to respect `Cargo.toml` while formatting a single buffer.

**Comment by lassik** [comment]
Thanks for reporting the bug. I don't use Rust myself, so I'll follow your recommendations on what to do.

Skimming that rustfmt thread, I got the impression that the problem is there's no simple way to run `rustfmt` so that it parses the same config file `cargo fmt` parses. And when we run `cargo fmt` we are almost guaranteed to format extra files in addition to the one we want.

**Comment by lassik** [comment]
Does this imply that Rust formatting currently cannot be made work properly for projects using non-standard formatter settings? In other words, we need to wait for the rustfmt and/or cargo fmt maintainers to add a command line flag for editor plugins.

**Comment by jenanwise** [comment]
> Skimming that rustfmt thread, I got the impression that the problem is there's no simple way to run rustfmt so that it parses the same config file cargo fmt parses. And when we run cargo fmt we are almost guaranteed to format extra files in addition to the one we want.

That's correct, at least for now.

> Does this imply that Rust formatting currently cannot be made work properly for projects using non-standard formatter settings?

Not quite. `rustfmt` respects settings in the project's `rustfmt.toml`. As far as I am aware, the only real rustfmt config option that matters in `Cargo.toml` is `edition`. By default, `rustfmt` uses the "2015" edition, which does not allow the `async` keyword. `Cargo.toml` specifies the Rust edition for the project, so using `cargo fmt` gets you automatic `edition` config for free, but other configuration options still go in `rustfmt.toml` (even when using `cargo fmt`).

It's worth noting that the [next major release](https://github.com/rust-lang/rustfmt/blob/0921e1fbf35a9ef414516f0ee73927baa8f186e0/CHANGELOG.md#changed) of `rustfmt` will default to the "2018" edition.

My recommendation would be to revert  #88 and advise users to create a `rustfmt.toml` if they need any configuration. That seems to be the recommendation for editor integrations from the rustlang team for now.

**Comment by lassik** [comment]
And you can set the edition in `rustfmt.toml` just as well as in `Cargo.toml`, so people using 2018 can solve their problem simply by creating the former file. That sounds very reasonable indeed. Let's do it.

**Comment by lassik** [comment]
OK, pushed a fix to master. Please test and close this issue if it solves the problem. Thanks for an excellent bug report!

**Comment by jenanwise** [comment]
It works, thank you!
