### ISSUE TITLE
setting indentation level

### ISSUE THREAD

**Issue by lanceberge** [lassik/emacs-format-all-the-code#96]
How do I set the indentation level for certain formattters? In my case, I want to use format-all-buffer to format .c files with 4 spaces, but it always sets it at 2. I have `c-basic-offset` set to 4 and `indent-tabs-mode` set to nil.

**Comment by lassik** [comment]
C is formatted using `clang-format`. You need to create a file named `.clang-format` in your project's directory. Here's the documentation for that file: http://clang.llvm.org/docs/ClangFormatStyleOptions.html Beware, clang-format has enough options to get lost in...

Format-all currently doesn't update your Emacs settings to match the clang-format file; that would be quite difficult to do reliably.

**Comment by lanceberge** [comment]
great, thanks!
